### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by SoundWavez97** [TheMaestro1s/Akinator-Bot#3]
hey pls add a function to auto stop for ex when it loses cuz after 48 clicks of buttons the questions are the same

**Comment by TheMaestro1s** [comment]
Should be **fixed** at this commit [976b8c5](https://github.com/TheMaestro1s/Akinator-Bot/commit/976b8c53e5f31630c89059569168a4cf6a682347).
Thanks for report!

**Comment by SoundWavez97** [comment]
> Should be **fixed** at this commit [976b8c5](https://github.com/TheMaestro1s/Akinator-Bot/commit/976b8c53e5f31630c89059569168a4cf6a682347). Thanks for report!

still doesnt work...u should probably test it
